query {
  products(first: 3, query: "vendor:Botanica") {
    nodes {
      title
      handle
      status
      totalInventory
      publishedOnCurrentPublication
      publishedOnShop
    }
  }
  shop {
    name
    productCount: productsCount { count }
  }
}
