mutation {
  productCreate(product: {
    title: "Test With Variant"
    vendor: "Botanica"
    status: ACTIVE
    productVariants: [{
      price: "29.99"
      optionValues: [{optionName: "Size", name: "6 inch"}]
    }]
  }) {
    product { id handle variants(first: 1) { nodes { id price } } }
    userErrors { field message }
  }
}
